mysite1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/create_vote/',views.create_vote,name='create_vote'),
    path('create_poll/',views.create_poll,name='create_poll'),
    path('post_poll/',views.post_poll,name='post_poll'),

]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	"""docstring for Question"""
	question_text = models.CharField(max_length=200)
	pub_date= models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text= models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.http import HttpResponse

from .models import *

# Create your views here.
def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')
	output = ', '.join([q.question_text for q in latest_question_list])
	context = {'latest_question_list':latest_question_list}		
	return render(request,'polls/index.html',context)

def detail(request, question_id):
	my_question = get_object_or_404(Question, pk = question_id)
	return HttpResponse("You're looking at question %s." % my_question.id)

def results(request, question_id):
	try:
		my_question = Question.objects.get(pk=question_id)
		context={"my_question":my_question}
		response = "You're looking at the results of question %s."
		return render(request,"polls/details.html",context)
	except Question.DoesNotExist:
		raise Http404("This page is not reachable!!!")

def create_vote(request,question_id):
	print('PKKK',question_id,"\n",request.POST)
	try:
		my_question = Question.objects.get(id=question_id)
		my_choice = my_question.choice_set.get(pk=request.POST['choice'])
		my_choice.votes+=1
		my_choice.save()
	except Exception as e:
			return HttpResponse("ERROR with create_vote",e)

	
	
	return redirect('/')


def create_poll(request):
	context={}
	return render(request,'polls/vote.html',context)

def post_poll(request):
	print('POSTKKK',"\n",request.POST,request.POST['choice1'])
	try:
		my_poll = Question(question_text=request.POST['question'], pub_date=timezone.now())
		my_poll.save()
		for a in range(1,len(request.POST)-1):
			choices = my_poll.choice_set.create(choice_text=request.POST['choice'+str(a)], votes=0)
		return redirect('/')
	except Exception as e:
		print(e)
		return HttpResponse("ERROR with create_vote",e)

polls/templates/polls/details.html
<!DOCTYPE html>
<html>
<head>
	<title>Details</title>
</head>
<body>
	{{my_question}}</br>
	{{my_question.id}}</br>
	{{my_question.pk}}</br>
	{{my_question.pub_date}}</br>
	{{my_question.question_text}}

	<ul>
		{% for choice in my_question.choice_set.all %}
			<li><a href="{% url 'polls:detail' my_question.id %}">{{choice.choice_text}} {{choice.votes}}</a></li>
			<!--	to use namespace like polls:detail you need to implement app_name = 'polls'  in polls/urls.py	--->


		{% endfor %}
	</ul>

</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Polls app</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">
</head>
<body>
	<div class="hero">
		<h1 style="font-size: 3em;">VoteMe</h1>
		<h3 style="font-size: 1.5em;">App for indecisive people</h3>
	</div>
	<a class="createNew" href="{% url 'polls:create_poll' %}">
		<span class="pipe v"></span>
		<span class="pipe h"></span>
	</a>
	<!-- <div class="filter">
		<div class='sortBy filter-box'>
			<h3 class="filter-text">Sort by:</h3>
			<span class="pipe"></span>
			<select class="filter-choice" value="choice">
			  <option value="Today">Today</option>
			  <option value="Week ago">Week ago</option>
			  <option value="Month ago">Month ago</option>
			  <option value="All">All</option>
			</select>

		</div>
		<div class='itemOnPage filter-box'>
			<h3 class="filter-text">On page:</h3>
			<span class="pipe"></span>
			<select class="filter-choice" value="5">
			  <option value="5">5</option>
			  <option value="10">10</option>
			  <option value="15">15</option>
			  <option value="20">20</option>
			</select>

		</div>
	</div> -->
	<div class="vote-wrapper">
		{% if latest_question_list %}
		{% for question in latest_question_list %}
		<div class="vote-card">
			<h1>{{question.question_text}}</h1>
			<h2>Choices:</h2>
			<form action="{% url 'polls:create_vote' question.id%}" method="POST">

			{% for choice in question.choice_set.all%}
			{% csrf_token%}
			<div class="label-box">
				<label>{{choice.choice_text}}</label>
				<input type="radio"  class="choice" name="choice" value={{choice.id}}>
				<span class="vote_counter">{{choice.votes}}</span>
			</div>
			{% endfor %}
			
			<input class="submit-btn" type="submit" name="">

			</form>
		</div>

		
		{% endfor %}

		{% else %}
		<center><p style="color: white;">No polls are available.</p></center>
		{% endif %}
	</div>
</body>
</html>

polls/templates/polls/newPoll.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Polls app</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'polls/newPoll.css' %}">
</head>
<body>
	
	
</body>
</html>

polls/templates/polls/vote.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/newPoll.css' %}">
	<title>votes</title>
</head>
<body>
	<div class="content">
		<h1>Create your own vote form</h1>
		<div class="form-wrapper">
			<form  class="form-group" action="{% url 'polls:post_poll'%}" method="POST"> 
				{% csrf_token%}
				<input type="text" id="name" class="form-control form-title" name="question"  required>
	        	<label class="form-control-placeholder form-title-ph" for="name">Title</label>
				<div id="pollFormChoice" class="choices-field">
					<div class="input-field">
						<input type="text" id="name" class="form-control" name="choice1"  required>
	        			<label class="form-control-placeholder" for="name">Choice</label>
					</div>
					<div class="input-field">
						<input type="text" id="name" class="form-control" name="choice2"  required>
	        			<label class="form-control-placeholder" for="name">Choice</label>
					</div>
					<div class="input-field">
						<input type="text" id="name" class="form-control" name="choice3"  required>
	        			<label class="form-control-placeholder" for="name">Choice</label>
					</div>
					<div class="input-field">
						<input type="text" id="name" class="form-control" name="choice4"  required>
	        			<label class="form-control-placeholder" for="name">Choice</label>
					</div>

				</div>
				

				<div class="form-btn-field">
					<input type="button" class="addChoice" value="add +" onclick="createNewPollField()">
				<input type="submit" class="submit" value="post">
				</div>
			</form>
		</div>
	</div>
<script type="text/javascript" src="{% static 'polls/createNewPollField.js' %}"></script>
</body>
</html>